"use client"

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import type { MyTag, Profile } from "@/types"

// PDF用のスタイル
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1a1a2e",
    backgroundColor: "#ffffff",
  },
  header: {
    borderBottom: "2px solid #3b82f6",
    paddingBottom: 12,
    marginBottom: 20,
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a2e",
    marginBottom: 4,
  },
  occupation: {
    fontSize: 12,
    color: "#6366f1",
    marginBottom: 8,
  },
  contactRow: {
    flexDirection: "row",
    gap: 16,
    fontSize: 9,
    color: "#6b7280",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#3b82f6",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
    marginTop: 16,
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: 4,
  },
  bodyText: {
    fontSize: 10,
    lineHeight: 1.6,
    color: "#374151",
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  tag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    fontSize: 9,
  },
  tagCommon: {
    backgroundColor: "#f3f4f6",
    color: "#6b7280",
  },
  tagRare: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
  },
  tagEpic: {
    backgroundColor: "#fdf4ff",
    color: "#a855f7",
  },
  tagLegendary: {
    backgroundColor: "#fefce8",
    color: "#ca8a04",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
    borderTop: "1px solid #e5e7eb",
    paddingTop: 8,
  },
})

const tagStyleMap = {
  common: styles.tagCommon,
  rare: styles.tagRare,
  epic: styles.tagEpic,
  legendary: styles.tagLegendary,
}

interface ResumeDocumentProps {
  profile: Profile
  tags: MyTag[]
}

export function ResumeDocument({ profile, tags }: ResumeDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{profile.name}</Text>
          <Text style={styles.occupation}>{profile.occupation || "未設定"}</Text>
          <View style={styles.contactRow}>
            {profile.contact_email && <Text>Email: {profile.contact_email}</Text>}
            <Text>ID: @{profile.id}</Text>
            <Text>Lv.{profile.level}</Text>
          </View>
        </View>

        {/* 自己PR */}
        {profile.bio && (
          <View>
            <Text style={styles.sectionTitle}>自己PR</Text>
            <Text style={styles.bodyText}>{profile.bio}</Text>
          </View>
        )}

        {/* 学歴・経歴 */}
        {profile.education && (
          <View>
            <Text style={styles.sectionTitle}>学歴・経歴</Text>
            <Text style={styles.bodyText}>{profile.education}</Text>
          </View>
        )}

        {/* スキル・実績 */}
        {tags.length > 0 && (
          <View>
            <Text style={styles.sectionTitle}>スキル・実績</Text>
            <View style={styles.tagContainer}>
              {tags.map((tag, i) => (
                <Text key={i} style={[styles.tag, tagStyleMap[tag.rarity]]}>
                  {tag.name} ({tag.rarity.toUpperCase()})
                </Text>
              ))}
            </View>
          </View>
        )}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by CYBER_STUDENT | {new Date().toISOString().split("T")[0].replace(/-/g, ".")}
        </Text>
      </Page>
    </Document>
  )
}
